# Generated by Django 5.2.7 on 2025-10-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_gpa', models.FloatField()),
                ('grade_letter', models.CharField(max_length=2)),
            ],
        ),
    ]
