# Generated by Django 5.2.7 on 2025-10-31 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gradecalc", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="graderesult",
            old_name="total_score_weighted",
            new_name="total_gpa",
        ),
    ]
