# Generated by Django 5.2.7 on 2025-10-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradecalc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graderesult',
            name='total_gpa',
        ),
        migrations.AddField(
            model_name='graderesult',
            name='total_score_weighted',
            field=models.FloatField(default=0.0),
        ),
    ]
