# Generated by Django 5.2.7 on 2025-11-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradecalc', '0002_rename_total_score_weighted_graderesult_total_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='graderesult',
            name='semester',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='graderesult',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
